name: ETL Workflow

on: [pull_request]

jobs:
  etl_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv
    - name: Install dependencies with uv
      run: |
        uv pip install . --system
    - name: Run ETL script
      run: python etl.py